type City = {
  countryCode: string;
  country: string;
  geonameid: number;
  name: string;
  subcountry: string;
};

export const statesConfig: Record<string, City[]> = {
  Kebbi: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2317548,
      name: "Zuru",
      subcountry: "Kebbi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335333,
      name: "Kamba",
      subcountry: "Kebbi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2336237,
      name: "Jega",
      subcountry: "Kebbi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347059,
      name: "Birnin Kebbi",
      subcountry: "Kebbi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2349431,
      name: "Argungu",
      subcountry: "Kebbi",
    },
  ],

  Niger: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2317569,
      name: "Zungeru",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2322263,
      name: "Tegina",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2322794,
      name: "Suleja",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2324504,
      name: "Rijau",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2329981,
      name: "Mokwa",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2330100,
      name: "Minna",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2332249,
      name: "Lapai",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2334008,
      name: "Kontagora",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339293,
      name: "Ibeto",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347209,
      name: "Bida",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347592,
      name: "Baro",
      subcountry: "Niger",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2348507,
      name: "Babana",
      subcountry: "Niger",
    },
  ],

  Kaduna: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2317765,
      name: "Zaria",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2322957,
      name: "Soba",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2332079,
      name: "Lere",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335614,
      name: "Kagoro",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335713,
      name: "Kafanchan",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335727,
      name: "Kaduna",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335798,
      name: "Kachia",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2344229,
      name: "Dutsen Wai",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347061,
      name: "Sofo-Birnin-Gwari",
      subcountry: "Kaduna",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2349951,
      name: "Anchau",
      subcountry: "Kaduna",
    },
  ],

  Adamawa: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2318044,
      name: "Yola",
      subcountry: "Adamawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328617,
      name: "Numan",
      subcountry: "Adamawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2329821,
      name: "Mubi",
      subcountry: "Adamawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2336056,
      name: "Jimeta",
      subcountry: "Adamawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2340446,
      name: "Gombi",
      subcountry: "Adamawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2341955,
      name: "Ganye",
      subcountry: "Adamawa",
    },
  ],

  Bayelsa: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2318123,
      name: "Yenagoa",
      subcountry: "Bayelsa",
    },
  ],

  Taraba: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2318921,
      name: "Wukari",
      subcountry: "Taraba",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2336589,
      name: "Jalingo",
      subcountry: "Taraba",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339287,
      name: "Ibi",
      subcountry: "Taraba",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2341275,
      name: "Gembu",
      subcountry: "Taraba",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347330,
      name: "Beli",
      subcountry: "Taraba",
    },
  ],

  Kano: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2318933,
      name: "Wudil",
      subcountry: "Kano",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2324575,
      name: "Rano",
      subcountry: "Kano",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335204,
      name: "Kano",
      subcountry: "Kano",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339756,
      name: "Gwarzo",
      subcountry: "Kano",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2341580,
      name: "Gaya",
      subcountry: "Kano",
    },
  ],

  Delta: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2319133,
      name: "Warri",
      subcountry: "Delta",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2320829,
      name: "Ughelli",
      subcountry: "Delta",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2323675,
      name: "Sapele",
      subcountry: "Delta",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327513,
      name: "Ogwashi-Uku",
      subcountry: "Delta",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2332871,
      name: "Kwale",
      subcountry: "Delta",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2346317,
      name: "Burutu",
      subcountry: "Delta",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2349276,
      name: "Asaba",
      subcountry: "Delta",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2351979,
      name: "Agbor",
      subcountry: "Delta",
    },
  ],

  Nassarawa: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2319257,
      name: "Wamba",
      subcountry: "Nassarawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2329451,
      name: "Nasarawa",
      subcountry: "Nassarawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2332515,
      name: "Lafia",
      subcountry: "Nassarawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2334652,
      name: "Keffi",
      subcountry: "Nassarawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2344600,
      name: "Doma",
      subcountry: "Nassarawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2350806,
      name: "Akwanga",
      subcountry: "Nassarawa",
    },
  ],

  "Akwa Ibom": [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2319480,
      name: "Uyo",
      subcountry: "Akwa Ibom",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2336985,
      name: "Itu",
      subcountry: "Akwa Ibom",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338106,
      name: "Ikot Ekpene",
      subcountry: "Akwa Ibom",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343093,
      name: "Esuk Oron",
      subcountry: "Akwa Ibom",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343720,
      name: "Eket",
      subcountry: "Akwa Ibom",
    },
  ],

  Edo: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2319668,
      name: "Uromi",
      subcountry: "Edo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2321031,
      name: "Ubiaja",
      subcountry: "Edo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343641,
      name: "Ekpoma",
      subcountry: "Edo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347283,
      name: "Benin City",
      subcountry: "Edo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2348892,
      name: "Auchi",
      subcountry: "Edo",
    },
  ],

  Abia: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2320576,
      name: "Umuahia",
      subcountry: "Abia",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327494,
      name: "Ohafia-Ifigh",
      subcountry: "Abia",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347303,
      name: "Bende",
      subcountry: "Abia",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2350249,
      name: "Amaigbo",
      subcountry: "Abia",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2353151,
      name: "Aba",
      subcountry: "Abia",
    },
  ],

  "Cross River": [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2320831,
      name: "Ugep",
      subcountry: "Cross River",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327650,
      name: "Ogoja",
      subcountry: "Cross River",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328151,
      name: "Obudu",
      subcountry: "Cross River",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338242,
      name: "Ikom",
      subcountry: "Cross River",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2346229,
      name: "Calabar",
      subcountry: "Cross River",
    },
  ],

  Anambra: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2320920,
      name: "Uga",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325161,
      name: "Ozubulu",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2326016,
      name: "Onitsha",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328765,
      name: "Nnewi",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328811,
      name: "Nkpor",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338497,
      name: "Ihiala",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338640,
      name: "Igbo-Ukwu",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343270,
      name: "Enugu-Ukwu",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2348773,
      name: "Awka",
      subcountry: "Anambra",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2351740,
      name: "Agulu",
      subcountry: "Anambra",
    },
  ],

  Sokoto: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2322495,
      name: "Tambuwal",
      subcountry: "Sokoto",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2322911,
      name: "Sokoto",
      subcountry: "Sokoto",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337680,
      name: "Illela",
      subcountry: "Sokoto",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339892,
      name: "Gwadabawa",
      subcountry: "Sokoto",
    },
  ],

  Zamfara: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2322529,
      name: "Talata Mafara",
      subcountry: "Zamfara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2329920,
      name: "Moriki",
      subcountry: "Zamfara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2334756,
      name: "Kaura Namoda",
      subcountry: "Zamfara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339937,
      name: "Gusau",
      subcountry: "Zamfara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2340086,
      name: "Gummi",
      subcountry: "Zamfara",
    },
  ],

  Benue: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2322552,
      name: "Takum",
      subcountry: "Benue",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325437,
      name: "Otukpa",
      subcountry: "Benue",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2331140,
      name: "Makurdi",
      subcountry: "Benue",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2334801,
      name: "Katsina-Ala",
      subcountry: "Benue",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338660,
      name: "Igbor",
      subcountry: "Benue",
    },
  ],

  Oyo: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2323390,
      name: "Saki",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325200,
      name: "Oyo",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325733,
      name: "Orita Eruwa",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2332357,
      name: "Lalupon",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2334327,
      name: "Kisi",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338669,
      name: "Igbo-Ora",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338711,
      name: "Igboho",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338772,
      name: "Igbeti",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339354,
      name: "Ibadan",
      subcountry: "Oyo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2342628,
      name: "Fiditi",
      subcountry: "Oyo",
    },
  ],

  Ogun: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2323411,
      name: "Shagamu",
      subcountry: "Ogun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337379,
      name: "Iperu",
      subcountry: "Ogun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337759,
      name: "Ilaro",
      subcountry: "Ogun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338400,
      name: "Ijebu-Ode",
      subcountry: "Ogun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338403,
      name: "Ijebu-Igbo",
      subcountry: "Ogun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338876,
      name: "Ifo",
      subcountry: "Ogun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2352356,
      name: "Ado Odo",
      subcountry: "Ogun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2352947,
      name: "Abeokuta",
      subcountry: "Ogun",
    },
  ],

  Yobe: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2324767,
      name: "Potiskum",
      subcountry: "Yobe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328952,
      name: "Nguru",
      subcountry: "Yobe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2333490,
      name: "Kumagunnam",
      subcountry: "Yobe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2341294,
      name: "Geidam",
      subcountry: "Yobe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2341656,
      name: "Gashua",
      subcountry: "Yobe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2345096,
      name: "Daura",
      subcountry: "Yobe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2345521,
      name: "Damaturu",
      subcountry: "Yobe",
    },
  ],

  Rivers: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2324774,
      name: "Port Harcourt",
      subcountry: "Rivers",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2326899,
      name: "Okrika",
      subcountry: "Rivers",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328185,
      name: "Obonoma",
      subcountry: "Rivers",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343512,
      name: "Elele",
      subcountry: "Rivers",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2346615,
      name: "Buguma",
      subcountry: "Rivers",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2346812,
      name: "Bonny",
      subcountry: "Rivers",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2591159,
      name: "Degema Hulk",
      subcountry: "Rivers",
    },
  ],

  Gombe: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2324857,
      name: "Pindiga",
      subcountry: "Gombe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2329562,
      name: "Nafada",
      subcountry: "Gombe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2333451,
      name: "Kumo",
      subcountry: "Gombe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2340451,
      name: "Gombe",
      subcountry: "Gombe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2341758,
      name: "Garko",
      subcountry: "Gombe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2344418,
      name: "Dukku",
      subcountry: "Gombe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2345029,
      name: "Deba",
      subcountry: "Gombe",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347155,
      name: "Billiri",
      subcountry: "Gombe",
    },
  ],

  Kwara: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2324960,
      name: "Patigi",
      subcountry: "Kwara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2326811,
      name: "Okuta",
      subcountry: "Kwara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327879,
      name: "Offa",
      subcountry: "Kwara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2332504,
      name: "Lafiagi",
      subcountry: "Kwara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335596,
      name: "Kaiama",
      subcountry: "Kwara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2336251,
      name: "Jebba",
      subcountry: "Kwara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337639,
      name: "Ilorin",
      subcountry: "Kwara",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2346951,
      name: "Bode Saadu",
      subcountry: "Kwara",
    },
  ],

  Plateau: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325060,
      name: "Pankshin",
      subcountry: "Plateau",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335953,
      name: "Jos",
      subcountry: "Plateau",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2346561,
      name: "Bukuru",
      subcountry: "Plateau",
    },
  ],

  Osun: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325249,
      name: "Oyan",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325506,
      name: "Otan Ayegbaju",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325590,
      name: "Osogbo",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2326302,
      name: "Olupona",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327223,
      name: "Oke Mesi",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2330028,
      name: "Modakeke",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2336905,
      name: "Iwo",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337490,
      name: "Inisa",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337659,
      name: "Ilobu",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337704,
      name: "Ilesa",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337765,
      name: "Ila Orangun",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338269,
      name: "Ikirun",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338273,
      name: "Ikire",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338401,
      name: "Ijebu-Jesa",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2341355,
      name: "Gbongan",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343784,
      name: "Ejigbo",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343983,
      name: "Effon Alaiye",
      subcountry: "Osun",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2349558,
      name: "Apomu",
      subcountry: "Osun",
    },
  ],

  Ondo: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325314,
      name: "Owo",
      subcountry: "Ondo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2326171,
      name: "Ondo",
      subcountry: "Ondo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328090,
      name: "Ode",
      subcountry: "Ondo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339150,
      name: "Idanre",
      subcountry: "Ondo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2350841,
      name: "Akure",
      subcountry: "Ondo",
    },
  ],

  Imo: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2325330,
      name: "Owerri",
      subcountry: "Imo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327143,
      name: "Okigwe",
      subcountry: "Imo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327521,
      name: "Oguta",
      subcountry: "Imo",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328790,
      name: "Nkwerre",
      subcountry: "Imo",
    },
  ],

  Kogi: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327220,
      name: "Okene",
      subcountry: "Kogi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327827,
      name: "Ogaminana",
      subcountry: "Kogi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2331939,
      name: "Lokoja",
      subcountry: "Kogi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335843,
      name: "Kabba",
      subcountry: "Kogi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337235,
      name: "Isanlu-Itedoijowa",
      subcountry: "Kogi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339156,
      name: "Idah",
      subcountry: "Kogi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343943,
      name: "Egbe",
      subcountry: "Kogi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2351470,
      name: "Ajaokuta",
      subcountry: "Kogi",
    },
  ],

  Ekiti: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2327233,
      name: "Oke Ila",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337207,
      name: "Ise-Ekiti",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337352,
      name: "Ipoti",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338287,
      name: "Ikere-Ekiti",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338385,
      name: "Ijero-Ekiti",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338630,
      name: "Igede-Ekiti",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338810,
      name: "Igbara-Odo",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343299,
      name: "Emure-Ekiti",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2349529,
      name: "Aramoko-Ekiti",
      subcountry: "Ekiti",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2352379,
      name: "Ado-Ekiti",
      subcountry: "Ekiti",
    },
  ],

  Enugu: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2328684,
      name: "Nsukka",
      subcountry: "Enugu",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343273,
      name: "Enugu-Ezike",
      subcountry: "Enugu",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343279,
      name: "Enugu",
      subcountry: "Enugu",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343822,
      name: "Eha Amufu",
      subcountry: "Enugu",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2348783,
      name: "Awgu",
      subcountry: "Enugu",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2350886,
      name: "Aku",
      subcountry: "Enugu",
    },
  ],

  Borno: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2329946,
      name: "Monguno",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2330719,
      name: "Marte",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2331447,
      name: "Maiduguri",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2331528,
      name: "Magumeri",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2333563,
      name: "Kukawa",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339665,
      name: "Gwoza",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2342192,
      name: "Gamboru",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2344854,
      name: "Dikwa",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2345498,
      name: "Damboa",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2346995,
      name: "Biu",
      subcountry: "Borno",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347954,
      name: "Bama",
      subcountry: "Borno",
    },
  ],

  Katsina: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2331005,
      name: "Malumfashi",
      subcountry: "Katsina",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2334802,
      name: "Katsina",
      subcountry: "Katsina",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2342490,
      name: "Funtua",
      subcountry: "Katsina",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2345094,
      name: "Daura",
      subcountry: "Katsina",
    },
  ],

  Lagos: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2331158,
      name: "Makoko",
      subcountry: "Lagos",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2332459,
      name: "Lagos",
      subcountry: "Lagos",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2338313,
      name: "Ikeja",
      subcountry: "Lagos",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343252,
      name: "Epe",
      subcountry: "Lagos",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2344082,
      name: "Ebute Ikorodu",
      subcountry: "Lagos",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2348395,
      name: "Badagry",
      subcountry: "Lagos",
    },
  ],

  "Abuja Federal Capital Territory": [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2333604,
      name: "Kuje",
      subcountry: "Abuja Federal Capital Territory",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2352778,
      name: "Abuja",
      subcountry: "Abuja Federal Capital Territory",
    },
  ],

  Jigawa: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2334306,
      name: "Kiyawa",
      subcountry: "Jigawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339631,
      name: "Hadejia",
      subcountry: "Jigawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2339786,
      name: "Gwaram",
      subcountry: "Jigawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2340091,
      name: "Gumel",
      subcountry: "Jigawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2344245,
      name: "Dutse",
      subcountry: "Jigawa",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347057,
      name: "Birnin Kudu",
      subcountry: "Jigawa",
    },
  ],

  Bauchi: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2335015,
      name: "Kari",
      subcountry: "Bauchi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2345152,
      name: "Darazo",
      subcountry: "Bauchi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2347470,
      name: "Bauchi",
      subcountry: "Bauchi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2348595,
      name: "Azare",
      subcountry: "Bauchi",
    },
  ],

  Ebonyi: [
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2337148,
      name: "Isieke",
      subcountry: "Ebonyi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2342883,
      name: "Ezza-Ohu",
      subcountry: "Ebonyi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2343985,
      name: "Effium",
      subcountry: "Ebonyi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2352250,
      name: "Afikpo",
      subcountry: "Ebonyi",
    },
    {
      countryCode: "ng",
      country: "Nigeria",
      geonameid: 2353099,
      name: "Abakaliki",
      subcountry: "Ebonyi",
    },
  ],
};
