type flag = {
  countryCode: string;
  countryName: string;
  default: boolean;
};

export const flagsConfig: flag[] = [
  // { countryCode: "ad", countryName: "Andorra", default: false },
  // { countryCode: "ae", countryName: "United Arab Emirates", default: false },
  // { countryCode: "af", countryName: "Afghanistan", default: false },
  // { countryCode: "ag", countryName: "Antigua and Barbuda", default: false },
  // { countryCode: "ai", countryName: "Anguilla", default: false },
  // { countryCode: "al", countryName: "Albania", default: false },
  // { countryCode: "am", countryName: "Armenia", default: false },
  // { countryCode: "ao", countryName: "Angola", default: false },
  // { countryCode: "aq", countryName: "Antarctica", default: false },
  // { countryCode: "ar", countryName: "Argentina", default: false },
  // { countryCode: "as", countryName: "American Samoa", default: false },
  // { countryCode: "at", countryName: "Austria", default: false },
  // { countryCode: "au", countryName: "Australia", default: false },
  // { countryCode: "aw", countryName: "Aruba", default: false },
  // { countryCode: "ax", countryName: "Åland Islands", default: false },
  // { countryCode: "az", countryName: "Azerbaijan", default: false },
  // { countryCode: "ba", countryName: "Bosnia and Herzegovina", default: false },
  // { countryCode: "bb", countryName: "Barbados", default: false },
  // { countryCode: "bd", countryName: "Bangladesh", default: false },
  // { countryCode: "be", countryName: "Belgium", default: false },
  // { countryCode: "bf", countryName: "Burkina Faso", default: false },
  // { countryCode: "bg", countryName: "Bulgaria", default: false },
  // { countryCode: "bh", countryName: "Bahrain", default: false },
  // { countryCode: "bi", countryName: "Burundi", default: false },
  // { countryCode: "bj", countryName: "Benin", default: false },
  // { countryCode: "bl", countryName: "Saint Barthélemy", default: false },
  // { countryCode: "bm", countryName: "Bermuda", default: false },
  // { countryCode: "bn", countryName: "Brunei", default: false },
  // { countryCode: "bo", countryName: "Bolivia", default: false },
  // { countryCode: "bq", countryName: "Caribbean Netherlands", default: false },
  // { countryCode: "br", countryName: "Brazil", default: false },
  // { countryCode: "bs", countryName: "Bahamas", default: false },
  // { countryCode: "bt", countryName: "Bhutan", default: false },
  // { countryCode: "bv", countryName: "Bouvet Island", default: false },
  // { countryCode: "bw", countryName: "Botswana", default: false },
  // { countryCode: "by", countryName: "Belarus", default: false },
  // { countryCode: "bz", countryName: "Belize", default: false },
  // { countryCode: "ca", countryName: "Canada", default: false },
  // { countryCode: "cc", countryName: "Cocos (Keeling) Islands", default: false },
  // { countryCode: "cd", countryName: "DR Congo", default: false },
  // {
  //   countryCode: "cf",
  //   countryName: "Central African Republic",
  //   default: false,
  // },
  // { countryCode: "cg", countryName: "Republic of the Congo", default: false },
  // { countryCode: "ch", countryName: "Switzerland", default: false },
  // {
  //   countryCode: "ci",
  //   countryName: "Côte d'Ivoire (Ivory Coast)",
  //   default: false,
  // },
  // { countryCode: "ck", countryName: "Cook Islands", default: false },
  // { countryCode: "cl", countryName: "Chile", default: false },
  // { countryCode: "cm", countryName: "Cameroon", default: false },
  // { countryCode: "cn", countryName: "China", default: false },
  // { countryCode: "co", countryName: "Colombia", default: false },
  // { countryCode: "cr", countryName: "Costa Rica", default: false },
  // { countryCode: "cu", countryName: "Cuba", default: false },
  // { countryCode: "cv", countryName: "Cape Verde", default: false },
  // { countryCode: "cw", countryName: "Curaçao", default: false },
  // { countryCode: "cx", countryName: "Christmas Island", default: false },
  // { countryCode: "cy", countryName: "Cyprus", default: false },
  // { countryCode: "cz", countryName: "Czechia", default: false },
  // { countryCode: "de", countryName: "Germany", default: false },
  // { countryCode: "dj", countryName: "Djibouti", default: false },
  // { countryCode: "dk", countryName: "Denmark", default: false },
  // { countryCode: "dm", countryName: "Dominica", default: false },
  // { countryCode: "do", countryName: "Dominican Republic", default: false },
  // { countryCode: "dz", countryName: "Algeria", default: false },
  // { countryCode: "ec", countryName: "Ecuador", default: false },
  // { countryCode: "ee", countryName: "Estonia", default: false },
  // { countryCode: "eg", countryName: "Egypt", default: false },
  // { countryCode: "eh", countryName: "Western Sahara", default: false },
  // { countryCode: "er", countryName: "Eritrea", default: false },
  // { countryCode: "es", countryName: "Spain", default: false },
  // { countryCode: "et", countryName: "Ethiopia", default: false },
  // { countryCode: "eu", countryName: "European Union", default: false },
  // { countryCode: "fi", countryName: "Finland", default: false },
  // { countryCode: "fj", countryName: "Fiji", default: false },
  // { countryCode: "fk", countryName: "Falkland Islands", default: false },
  // { countryCode: "fm", countryName: "Micronesia", default: false },
  // { countryCode: "fo", countryName: "Faroe Islands", default: false },
  // { countryCode: "fr", countryName: "France", default: false },
  // { countryCode: "ga", countryName: "Gabon", default: false },
  // { countryCode: "gb", countryName: "United Kingdom", default: false },
  // { countryCode: "gd", countryName: "Grenada", default: false },
  // { countryCode: "ge", countryName: "Georgia", default: false },
  // { countryCode: "gf", countryName: "French Guiana", default: false },
  // { countryCode: "gg", countryName: "Guernsey", default: false },
  // { countryCode: "gh", countryName: "Ghana", default: false },
  // { countryCode: "gi", countryName: "Gibraltar", default: false },
  // { countryCode: "gl", countryName: "Greenland", default: false },
  // { countryCode: "gm", countryName: "Gambia", default: false },
  // { countryCode: "gn", countryName: "Guinea", default: false },
  // { countryCode: "gp", countryName: "Guadeloupe", default: false },
  // { countryCode: "gq", countryName: "Equatorial Guinea", default: false },
  // { countryCode: "gr", countryName: "Greece", default: false },
  // { countryCode: "gs", countryName: "South Georgia", default: false },
  // { countryCode: "gt", countryName: "Guatemala", default: false },
  // { countryCode: "gu", countryName: "Guam", default: false },
  // { countryCode: "gw", countryName: "Guinea-Bissau", default: false },
  // { countryCode: "gy", countryName: "Guyana", default: false },
  // { countryCode: "hk", countryName: "Hong Kong", default: false },
  // {
  //   countryCode: "hm",
  //   countryName: "Heard Island and McDonald Islands",
  //   default: false,
  // },
  // { countryCode: "hn", countryName: "Honduras", default: false },
  // { countryCode: "hr", countryName: "Croatia", default: false },
  // { countryCode: "ht", countryName: "Haiti", default: false },
  // { countryCode: "hu", countryName: "Hungary", default: false },
  // { countryCode: "id", countryName: "Indonesia", default: false },
  // { countryCode: "ie", countryName: "Ireland", default: false },
  // { countryCode: "il", countryName: "Israel", default: false },
  // { countryCode: "im", countryName: "Isle of Man", default: false },
  // { countryCode: "in", countryName: "India", default: false },
  // {
  //   countryCode: "io",
  //   countryName: "British Indian Ocean Territory",
  //   default: false,
  // },
  // { countryCode: "iq", countryName: "Iraq", default: false },
  // { countryCode: "ir", countryName: "Iran", default: false },
  // { countryCode: "is", countryName: "Iceland", default: false },
  // { countryCode: "it", countryName: "Italy", default: false },
  // { countryCode: "je", countryName: "Jersey", default: false },
  // { countryCode: "jm", countryName: "Jamaica", default: false },
  // { countryCode: "jo", countryName: "Jordan", default: false },
  // { countryCode: "jp", countryName: "Japan", default: false },
  // { countryCode: "ke", countryName: "Kenya", default: false },
  // { countryCode: "kg", countryName: "Kyrgyzstan", default: false },
  // { countryCode: "kh", countryName: "Cambodia", default: false },
  // { countryCode: "ki", countryName: "Kiribati", default: false },
  // { countryCode: "km", countryName: "Comoros", default: false },
  // { countryCode: "kn", countryName: "Saint Kitts and Nevis", default: false },
  // { countryCode: "kp", countryName: "North Korea", default: false },
  // { countryCode: "kr", countryName: "South Korea", default: false },
  // { countryCode: "kw", countryName: "Kuwait", default: false },
  // { countryCode: "ky", countryName: "Cayman Islands", default: false },
  // { countryCode: "kz", countryName: "Kazakhstan", default: false },
  // { countryCode: "la", countryName: "Laos", default: false },
  // { countryCode: "lb", countryName: "Lebanon", default: false },
  // { countryCode: "lc", countryName: "Saint Lucia", default: false },
  // { countryCode: "li", countryName: "Liechtenstein", default: false },
  // { countryCode: "lk", countryName: "Sri Lanka", default: false },
  // { countryCode: "lr", countryName: "Liberia", default: false },
  // { countryCode: "ls", countryName: "Lesotho", default: false },
  // { countryCode: "lt", countryName: "Lithuania", default: false },
  // { countryCode: "lu", countryName: "Luxembourg", default: false },
  // { countryCode: "lv", countryName: "Latvia", default: false },
  // { countryCode: "ly", countryName: "Libya", default: false },
  // { countryCode: "ma", countryName: "Morocco", default: false },
  // { countryCode: "mc", countryName: "Monaco", default: false },
  // { countryCode: "md", countryName: "Moldova", default: false },
  // { countryCode: "me", countryName: "Montenegro", default: false },
  // { countryCode: "mf", countryName: "Saint Martin", default: false },
  // { countryCode: "mg", countryName: "Madagascar", default: false },
  // { countryCode: "mh", countryName: "Marshall Islands", default: false },
  // { countryCode: "mk", countryName: "North Macedonia", default: false },
  // { countryCode: "ml", countryName: "Mali", default: false },
  // { countryCode: "mm", countryName: "Myanmar", default: false },
  // { countryCode: "mn", countryName: "Mongolia", default: false },
  // { countryCode: "mo", countryName: "Macau", default: false },
  // {
  //   countryCode: "mp",
  //   countryName: "Northern Mariana Islands",
  //   default: false,
  // },
  // { countryCode: "mq", countryName: "Martinique", default: false },
  // { countryCode: "mr", countryName: "Mauritania", default: false },
  // { countryCode: "ms", countryName: "Montserrat", default: false },
  // { countryCode: "mt", countryName: "Malta", default: false },
  // { countryCode: "mu", countryName: "Mauritius", default: false },
  // { countryCode: "mv", countryName: "Maldives", default: false },
  // { countryCode: "mw", countryName: "Malawi", default: false },
  // { countryCode: "mx", countryName: "Mexico", default: false },
  // { countryCode: "my", countryName: "Malaysia", default: false },
  // { countryCode: "mz", countryName: "Mozambique", default: false },
  // { countryCode: "na", countryName: "Namibia", default: false },
  // { countryCode: "nc", countryName: "New Caledonia", default: false },
  // { countryCode: "ne", countryName: "Niger", default: false },
  // { countryCode: "nf", countryName: "Norfolk Island", default: false },
  { countryCode: "ng", countryName: "Nigeria", default: true },
  // { countryCode: "ni", countryName: "Nicaragua", default: false },
  // { countryCode: "nl", countryName: "Netherlands", default: false },
  // { countryCode: "no", countryName: "Norway", default: false },
  // { countryCode: "np", countryName: "Nepal", default: false },
  // { countryCode: "nr", countryName: "Nauru", default: false },
  // { countryCode: "nu", countryName: "Niue", default: false },
  // { countryCode: "nz", countryName: "New Zealand", default: false },
  // { countryCode: "om", countryName: "Oman", default: false },
  // { countryCode: "pa", countryName: "Panama", default: false },
  // { countryCode: "pe", countryName: "Peru", default: false },
  // { countryCode: "pf", countryName: "French Polynesia", default: false },
  // { countryCode: "pg", countryName: "Papua New Guinea", default: false },
  // { countryCode: "ph", countryName: "Philippines", default: false },
  // { countryCode: "pk", countryName: "Pakistan", default: false },
  // { countryCode: "pl", countryName: "Poland", default: false },
  // {
  //   countryCode: "pm",
  //   countryName: "Saint Pierre and Miquelon",
  //   default: false,
  // },
  // { countryCode: "pn", countryName: "Pitcairn Islands", default: false },
  // { countryCode: "pr", countryName: "Puerto Rico", default: false },
  // { countryCode: "ps", countryName: "Palestine", default: false },
  // { countryCode: "pt", countryName: "Portugal", default: false },
  // { countryCode: "pw", countryName: "Palau", default: false },
  // { countryCode: "py", countryName: "Paraguay", default: false },
  // { countryCode: "qa", countryName: "Qatar", default: false },
  // { countryCode: "re", countryName: "Réunion", default: false },
  // { countryCode: "ro", countryName: "Romania", default: false },
  // { countryCode: "rs", countryName: "Serbia", default: false },
  // { countryCode: "ru", countryName: "Russia", default: false },
  // { countryCode: "rw", countryName: "Rwanda", default: false },
  // { countryCode: "sa", countryName: "Saudi Arabia", default: false },
  // { countryCode: "sb", countryName: "Solomon Islands", default: false },
  // { countryCode: "sc", countryName: "Seychelles", default: false },
  // { countryCode: "sd", countryName: "Sudan", default: false },
  // { countryCode: "se", countryName: "Sweden", default: false },
  // { countryCode: "sg", countryName: "Singapore", default: false },
  // {
  //   countryCode: "sh",
  //   countryName: "Saint Helena, Ascension and Tristan da Cunha",
  //   default: false,
  // },
  // { countryCode: "si", countryName: "Slovenia", default: false },
  // { countryCode: "sj", countryName: "Svalbard and Jan Mayen", default: false },
  // { countryCode: "sk", countryName: "Slovakia", default: false },
  // { countryCode: "sl", countryName: "Sierra Leone", default: false },
  // { countryCode: "sm", countryName: "San Marino", default: false },
  // { countryCode: "sn", countryName: "Senegal", default: false },
  // { countryCode: "so", countryName: "Somalia", default: false },
  // { countryCode: "sr", countryName: "Suriname", default: false },
  // { countryCode: "ss", countryName: "South Sudan", default: false },
  // { countryCode: "st", countryName: "São Tomé and Príncipe", default: false },
  // { countryCode: "sv", countryName: "El Salvador", default: false },
  // { countryCode: "sx", countryName: "Sint Maarten", default: false },
  // { countryCode: "sy", countryName: "Syria", default: false },
  // { countryCode: "sz", countryName: "Eswatini (Swaziland)", default: false },
  // {
  //   countryCode: "tc",
  //   countryName: "Turks and Caicos Islands",
  //   default: false,
  // },
  // { countryCode: "td", countryName: "Chad", default: false },
  // {
  //   countryCode: "tf",
  //   countryName: "French Southern and Antarctic Lands",
  //   default: false,
  // },
  // { countryCode: "tg", countryName: "Togo", default: false },
  // { countryCode: "th", countryName: "Thailand", default: false },
  // { countryCode: "tj", countryName: "Tajikistan", default: false },
  // { countryCode: "tk", countryName: "Tokelau", default: false },
  // { countryCode: "tl", countryName: "Timor-Leste", default: false },
  // { countryCode: "tm", countryName: "Turkmenistan", default: false },
  // { countryCode: "tn", countryName: "Tunisia", default: false },
  // { countryCode: "to", countryName: "Tonga", default: false },
  // { countryCode: "tr", countryName: "Turkey", default: false },
  // { countryCode: "tt", countryName: "Trinidad and Tobago", default: false },
  // { countryCode: "tv", countryName: "Tuvalu", default: false },
  // { countryCode: "tw", countryName: "Taiwan", default: false },
  // { countryCode: "tz", countryName: "Tanzania", default: false },
  // { countryCode: "ua", countryName: "Ukraine", default: false },
  // { countryCode: "ug", countryName: "Uganda", default: false },
  // {
  //   countryCode: "um",
  //   countryName: "United States Minor Outlying Islands",
  //   default: false,
  // },
  // { countryCode: "un", countryName: "United Nations", default: false },
  // { countryCode: "us", countryName: "United States", default: false },
  // { countryCode: "uy", countryName: "Uruguay", default: false },
  // { countryCode: "uz", countryName: "Uzbekistan", default: false },
  // { countryCode: "va", countryName: "Vatican City (Holy See)", default: false },
  // {
  //   countryCode: "vc",
  //   countryName: "Saint Vincent and the Grenadines",
  //   default: false,
  // },
  // { countryCode: "ve", countryName: "Venezuela", default: false },
  // { countryCode: "vg", countryName: "British Virgin Islands", default: false },
  // {
  //   countryCode: "vi",
  //   countryName: "United States Virgin Islands",
  //   default: false,
  // },
  // { countryCode: "vn", countryName: "Vietnam", default: false },
  // { countryCode: "vu", countryName: "Vanuatu", default: false },
  // { countryCode: "wf", countryName: "Wallis and Futuna", default: false },
  // { countryCode: "ws", countryName: "Samoa", default: false },
  // { countryCode: "xk", countryName: "Kosovo", default: false },
  // { countryCode: "ye", countryName: "Yemen", default: false },
  // { countryCode: "yt", countryName: "Mayotte", default: false },
  // { countryCode: "za", countryName: "South Africa", default: false },
  // { countryCode: "zm", countryName: "Zambia", default: false },
  // { countryCode: "zw", countryName: "Zimbabwe", default: false },
];
